---
version: 2.2.3
services:
  database:
    image: postgres
    env_file:
    - "./.docker/.env"
    volumes:
    - "./.docker/volumes/database:/var/lib/postgresql/data"
  web:
    build:
      context: "."
      dockerfile: "./.docker/Dockerfile"
    env_file:
    - "./.docker/.env"
    volumes:
    - "./ror:/ror"
    ports:
    - 3001:3000
    depends_on:
    - database
    command: run-app
